name: motofix_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # This is the corrected SDK constraint. It allows any version
  # from 3.4.0 up to (but not including) 4.0.0.
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0

  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.3
  multi_select_flutter: ^4.1.3
  uuid: ^4.5.1
  dartz: ^0.10.1
  path_provider: ^2.1.5
  equatable: ^2.0.7
  image_picker: ^1.1.2
  awesome_dio_interceptor: ^1.3.0
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.0+1
  another_flushbar: ^1.12.30
  lottie: ^3.3.1
  intl_phone_field: ^3.2.0
  cupertino_icons: ^1.0.8
  json_serializable: ^6.9.0
  hive: ^2.2.3
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  build_runner: ^2.5.2  
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  url_launcher: ^6.0.12
  font_awesome_flutter: ^10.4.0

  
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  
  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: RogueScript
    fonts:
      - asset: assets/fonts/RougeScript-Regular.ttf

  - family: AbrilFatface
    fonts:
      - asset: assets/fonts/AbrilFatface-Regular.ttf

  - family: Lato
    fonts:
      - asset: assets/fonts/Lato-Regular.ttf

  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


